FROM registry.federation.mip.hbp/mip_base/r-libs:latest

# Initial code from https://github.com/cardcorp/card-rocker/tree/master/r-java
# MAINTAINER Gergely Daroczi <gergely.daroczi@card.com>
MAINTAINER ludovic.claude54@gmail.com

COPY scripts/setup.sh /usr/local/bin/r-java-docker-setup

RUN /usr/local/bin/r-java-docker-setup
