FROM hbpmip/java-mip:latest

MAINTAINER arnaud@ahead-solutions.ch

ENV JAVA_CLASSPATH=./dist/java-rapidminer.jar
ENV JAVA_MAINCLASS=eu.hbp.mip.container.rapidminer.Main

COPY target/java-rapidminer.jar /dist/java-rapidminer.jar
