FROM hbpmip/java-mip:latest

MAINTAINER arnaud@ahead-solutions.ch

ENV JAVA_CLASSPATH=./dist/java-rapidminer.jar
ENV JAVA_MAINCLASS=ch.lren.hbpmip.rapidminer.Main

COPY target/java-rapidminer.jar /dist/java-rapidminer.jar
